<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Help SRN Information</title>
</head>
<body>

    <p>
        Hi, A new service request has been generated by client. The details of the request are mentioned below:
    </p>

    <p><strong>Name:</strong> {{ ucfirst($user->name) }}</p>
    <p><strong>Brand:</strong> {{ ucfirst($ticket->job) }}</p>
    <p><strong>Title:</strong> {{ ucfirst($help->title) }}</p>
    <p><strong>Case ID:</strong> {{ ucfirst($help->case_id) }}</p>
    <p><strong>Summary:</strong> {!! $help->summary !!}</p>
</body>
</html>
